########################################################
### development env             
########################################################
FROM node:16.13.1-alpine

WORKDIR /root/src/app

RUN apk add bash

EXPOSE 443